### ISSUE TITLE
computer independent paths in settings

### ISSUE THREAD

**Issue by gedw99** [tockins/realize#120]
At the moment it puts the full absolute path, when really you want the $GOPATH, because its then go install location independent.

path: $GOPATH/github.com/me/proj01/cmd/my-ui

```
settings:
  resources:
    outputs: outputs.log
    logs: logs.log
    errors: errors.log
  server:
    status: true
    open: false
    host: localhost
    port: 5001
projects:
- name: my-ui
path: $GOPATH/github.com/me/proj01/cmd/my-ui
```
