### ISSUE TITLE
Support build with custom bin path

### ISSUE THREAD

**Issue by conventi** [tockins/realize#130]
We need to support builds with custom output path (-o parameter). 

Example:
```
 - name: go-realize-test
   path: /Users/username/go/src/github.com/githubuser/go-realize-test
   commands:
     build:
       method: go build -o bin/go-realize-test ./cmd/go-realize-test
       status: true
     run: true
```
