### ISSUE TITLE
watch stops working after 1st save

### ISSUE THREAD

**Issue by jhartman86** [tockins/realize#149]
The watcher seems to stop working after the first time a file gets saved, **until** another file gets saved. The app doesn't crash or exit; and the watcher _does_ continue running - but it won't restart/do-whatever-is-configured.

Here's what happens exactly: say files A.go and B.go exist. Realize has started and completed a build for the first time. File A gets changed and saved, and realize detects its and runs a build. Another change is made to file A and saved - _realize doesn't do anything_. If you edit file B and save it, realize will detect and run a build. Now if you go back and change file A again and save it, realize runs again. So on and so forth.

It feels like some kind of caching mechanism against the filename might be causing issues, but just a hunch.

Let me know if any other system or config info would be helpful to figure this out.

---

realize.yml file:
```
settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: 0.0.0.0
schema:
- name: appname
  path: .
  commands:
    fmt:
      status: true
    install:
      status: true
    run:
      status: true
  args:
  - service
  - run
  - --all
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
```

**Comment by Asoseil** [comment]
Could be related to #144

**Comment by jhartman86** [comment]
@Asoseil that sounds like the exact issue I'm seeing as well. Whatever I can do to contribute to helping resolve this, just let me know.

**Comment by Asoseil** [comment]
it would be great you could help, otherwise I'll check in the next days

**Comment by Asoseil** [comment]
could you retry after an update?

**Comment by jhartman86** [comment]
@Asoseil absolutely. just let me know when and what you want me to do

**Comment by Asoseil** [comment]
should be fixed with last master commit, let me know if it works, i have no more problems on macos

**Comment by jhartman86** [comment]
@Asoseil didn't seem to work. deleted realize from the /src directory and the installed binary from /bin, then reinstalled via `go get`, and confirmed the latest commit hash was `a039601914fae96a926fed72b0d5380773f6ff56`. can you confirm that should include the fix?

That said - the prompt response doesn't go unappreciated; much obliged for the quick turnaround. Lmk if I can provide any other info to help with this. Still planning to use (and recommend) realize for all projects going forward.

**Comment by Asoseil** [comment]
Try in this way:
```
go get -u github.com/tockins/realize
```
enable debug in your realize config

```
settings:
  recovery:
    events: true
    tools: false
  legacy:
```
post the logs after each change as #144
