### ISSUE TITLE
Allow extension wildcard and add ignored_extensions

### ISSUE THREAD

**Issue by bryaan** [tockins/realize#156]
I have a project where I have many more extensions I want to track than not track.  Rather than write 100 extensions and keep it up to date, it would be better to allow all extensions and blacklist the ones I don't want to track.  

I'm thinking it would look something like:
```yaml
  watcher:
    extensions:
    - *
    ignored_extensions:
    - DS_Store
```

By default if no extensions are given the wildcard option should be assumed.  After all, why run at all if not tracking any files - like it does now if no extensions are specified?

Also, I find myself wondering why we need to specify extensions at all if we have include directories.  This problem shows the need for the requested features.

Can we do this?
