### ISSUE TITLE
Run webpack when js file changes

### ISSUE THREAD

**Issue by rizkyramadhan** [tockins/realize#161]
I want to start `yarn build` command whenever js file changes, how to do that in realize ?

**Comment by jhuss** [comment]
it's simple, add schema for js, like this:

```yaml
schema:
- name: js-stuff
  path: .
  commands: {}
  watcher:
    paths:
    - /
    extensions:
    - js
    ignored_paths:
    - .git
    - .realize
    - vendor
    - node_modules
    - dist
    scripts:
    - type: after
      command: ./node_modules/.bin/webpack index.js dist/bundle.js
      output: true
```

it's just a very simple example, play with paths, scripts, and commands
