### ISSUE TITLE
projects.watcher.scripts only working at startup

### ISSUE THREAD

**Issue by azr** [tockins/realize#56]
Howdy,

I have a command under `projects.watcher.scripts` that runs a bash to generate a golang file and it is only ran at startup, not on reiteration of the file changes.

```
- name: go-admin
  path: .
  fmt: true
  generate: false
  test: false
  bin: true
  build: false
  run: true
  watcher:
    preview: false
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    scripts:
    - type: before
      command: ./gotify.sh # transform some html templates into golang temapltes.Must variables set
      path: templates
  streams:
    cli_out: true
    file_out: false
    file_log: false
    file_err: false
```
