### ISSUE TITLE
Remote WebServer call localhost WebSocket

### ISSUE THREAD

**Issue by m4dfry** [tockins/realize#78]
Hi,
I found a problem launching server on my remote machine; the address of websocket appears to be broken.
Connecting to < my-ip >:5001 the web page try connect to ws://localhost:5001/ws

I located the problem in all.min.js (line: 92029)
`var ws = $websocket('ws://localhost:'+$location.port()+'/ws');`

Configuration YAML:
```
  server:
    status: true
    open: false
    host: ""
    port: 5001
```
