### ISSUE TITLE
realize.yaml is being overwritten after exit from realize

### ISSUE THREAD

**Issue by vinicio** [tockins/realize#85]
I'm trying to change my realize.yaml to match the [printer](https://github.com/tockins/realize-examples/blob/master/print/printer/.realize/realize.yaml) example, but my config file is being overwritten every time I exit from `realize run` and the new config is ignored.

By the way, I'm trying to make realize print my logs using [logrus](https://github.com/sirupsen/logrus), but it doesn't seem to attach a TTY to the output, so logs have been printed as plain text instead of pretty printed.

Thank you!

**Comment by Asoseil** [comment]
you can't' change the yaml file if "realize" is running. Could you attach your configuration? I'll check logrus

**Comment by vinicio** [comment]
realize is not running when I edit the file. I add lines to it, start "realize run", and when I stop it, my config file is back to the original. This is my file:

```yaml
settings:
  resources:
    outputs: outputs.log
    logs: logs.log
    errors: errors.log
  server:
    status: false
    open: false
    host: localhost
    port: 3001
projects:
- name: project
  path: .
  commands:
    vet: false
    fmt: false
    test: false
    generate: false
    bin:
      status: true
    build:
      status: false
    run: true
  watcher:
    preview: false
    paths:
    - /
    ignore_paths:
    - vendor
    - node_modules
    exts:
    - .go
    - .yml
    - .sql
```

The lines I'm trying to add:

```yaml
  streams:
    cli_out: true
    file_out: false
    file_log: false
    file_err: false
  errorOutputPattern: ""
```

I'm using Ubuntu 16.04, realize v1.4.1.
